package cn.edu.buu.uoes.dao;

import cn.edu.buu.uoes.pojo.ClassCourse;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface ClassCourseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Delete({
        "delete from class_course",
        "where clno = #{clno,jdbcType=INTEGER}",
          "and cno = #{cno,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("clno") Integer clno, @Param("cno") Integer cno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Insert({
        "insert into class_course (clno, cno)",
        "values (#{clno,jdbcType=INTEGER}, #{cno,jdbcType=INTEGER})"
    })
    int insert(ClassCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "clno, cno",
        "from class_course"
    })
    @ConstructorArgs({
        @Arg(column="clno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="cno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true)
    })
    List<ClassCourse> selectAll();
}