package cn.edu.buu.uoes.dao;

import cn.edu.buu.uoes.pojo.Classes;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ClassesDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Delete({
        "delete from classes",
        "where clno = #{clno,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer clno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Insert({
        "insert into classes (clno, class_name, ",
        "tno)",
        "values (#{clno,jdbcType=INTEGER}, #{className,jdbcType=VARCHAR}, ",
        "#{tno,jdbcType=INTEGER})"
    })
    int insert(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "clno, class_name, tno",
        "from classes",
        "where clno = #{clno,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="clno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="class_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="tno", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    Classes selectByPrimaryKey(Integer clno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "clno, class_name, tno",
        "from classes"
    })
    @ConstructorArgs({
        @Arg(column="clno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="class_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="tno", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    List<Classes> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Update({
        "update classes",
        "set class_name = #{className,jdbcType=VARCHAR},",
          "tno = #{tno,jdbcType=INTEGER}",
        "where clno = #{clno,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Classes record);
}