package cn.edu.buu.uoes.dao;

import cn.edu.buu.uoes.pojo.Course;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface CourseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Delete({
        "delete from course",
        "where cno = #{cno,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer cno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Insert({
        "insert into course (cno, course_name, ",
        "tno)",
        "values (#{cno,jdbcType=INTEGER}, #{courseName,jdbcType=VARCHAR}, ",
        "#{tno,jdbcType=INTEGER})"
    })
    int insert(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "cno, course_name, tno",
        "from course",
        "where cno = #{cno,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="cno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="course_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="tno", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    Course selectByPrimaryKey(Integer cno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "cno, course_name, tno",
        "from course"
    })
    @ConstructorArgs({
        @Arg(column="cno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="course_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="tno", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    List<Course> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Update({
        "update course",
        "set course_name = #{courseName,jdbcType=VARCHAR},",
          "tno = #{tno,jdbcType=INTEGER}",
        "where cno = #{cno,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Course record);
}