package cn.edu.buu.uoes.dao;

import cn.edu.buu.uoes.pojo.Exam;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ExamDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Delete({
        "delete from exam",
        "where eno = #{eno,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer eno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Insert({
        "insert into exam (eno, cno, ",
        "point)",
        "values (#{eno,jdbcType=INTEGER}, #{cno,jdbcType=INTEGER}, ",
        "#{point,jdbcType=INTEGER})"
    })
    int insert(Exam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "eno, cno, point",
        "from exam",
        "where eno = #{eno,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="eno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="cno", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="point", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    Exam selectByPrimaryKey(Integer eno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "eno, cno, point",
        "from exam"
    })
    @ConstructorArgs({
        @Arg(column="eno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="cno", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="point", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    List<Exam> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Update({
        "update exam",
        "set cno = #{cno,jdbcType=INTEGER},",
          "point = #{point,jdbcType=INTEGER}",
        "where eno = #{eno,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Exam record);
}