package cn.edu.buu.uoes.dao;

import cn.edu.buu.uoes.pojo.ExamQuestion;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface ExamQuestionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Delete({
        "delete from exam_question",
        "where eno = #{eno,jdbcType=INTEGER}",
          "and qno = #{qno,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("eno") Integer eno, @Param("qno") Integer qno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Insert({
        "insert into exam_question (eno, qno)",
        "values (#{eno,jdbcType=INTEGER}, #{qno,jdbcType=INTEGER})"
    })
    int insert(ExamQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "eno, qno",
        "from exam_question"
    })
    @ConstructorArgs({
        @Arg(column="eno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="qno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true)
    })
    List<ExamQuestion> selectAll();
}