package cn.edu.buu.uoes.dao;

import cn.edu.buu.uoes.pojo.Question;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface QuestionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Delete({
        "delete from question",
        "where qno = #{qno,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer qno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Insert({
        "insert into question (qno, question, ",
        "type, cno)",
        "values (#{qno,jdbcType=INTEGER}, #{question,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=INTEGER}, #{cno,jdbcType=INTEGER})"
    })
    int insert(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "qno, question, type, cno",
        "from question",
        "where qno = #{qno,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="qno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="question", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="type", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="cno", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    Question selectByPrimaryKey(Integer qno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "qno, question, type, cno",
        "from question"
    })
    @ConstructorArgs({
        @Arg(column="qno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="question", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="type", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="cno", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    List<Question> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Update({
        "update question",
        "set question = #{question,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "cno = #{cno,jdbcType=INTEGER}",
        "where qno = #{qno,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Question record);
}