package cn.edu.buu.uoes.dao;

import cn.edu.buu.uoes.pojo.Result;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ResultDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Delete({
        "delete from result",
        "where tsno = #{tsno,jdbcType=INTEGER}",
          "and qno = #{qno,jdbcType=INTEGER}",
          "and sno = #{sno,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("tsno") Integer tsno, @Param("qno") Integer qno, @Param("sno") Integer sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Insert({
        "insert into result (tsno, qno, ",
        "sno, seno)",
        "values (#{tsno,jdbcType=INTEGER}, #{qno,jdbcType=INTEGER}, ",
        "#{sno,jdbcType=INTEGER}, #{seno,jdbcType=INTEGER})"
    })
    int insert(Result record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "tsno, qno, sno, seno",
        "from result",
        "where tsno = #{tsno,jdbcType=INTEGER}",
          "and qno = #{qno,jdbcType=INTEGER}",
          "and sno = #{sno,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="tsno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="qno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="sno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="seno", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    Result selectByPrimaryKey(@Param("tsno") Integer tsno, @Param("qno") Integer qno, @Param("sno") Integer sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "tsno, qno, sno, seno",
        "from result"
    })
    @ConstructorArgs({
        @Arg(column="tsno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="qno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="sno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="seno", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    List<Result> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Update({
        "update result",
        "set seno = #{seno,jdbcType=INTEGER}",
        "where tsno = #{tsno,jdbcType=INTEGER}",
          "and qno = #{qno,jdbcType=INTEGER}",
          "and sno = #{sno,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Result record);
}