package cn.edu.buu.uoes.dao;

import cn.edu.buu.uoes.pojo.Score;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ScoreDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Delete({
        "delete from score",
        "where sno = #{sno,jdbcType=INTEGER}",
          "and cno = #{cno,jdbcType=INTEGER}",
          "and tsno = #{tsno,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("sno") Integer sno, @Param("cno") Integer cno, @Param("tsno") Integer tsno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Insert({
        "insert into score (sno, cno, ",
        "tsno, score)",
        "values (#{sno,jdbcType=INTEGER}, #{cno,jdbcType=INTEGER}, ",
        "#{tsno,jdbcType=INTEGER}, #{score,jdbcType=INTEGER})"
    })
    int insert(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "sno, cno, tsno, score",
        "from score",
        "where sno = #{sno,jdbcType=INTEGER}",
          "and cno = #{cno,jdbcType=INTEGER}",
          "and tsno = #{tsno,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="sno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="cno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="tsno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="score", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    Score selectByPrimaryKey(@Param("sno") Integer sno, @Param("cno") Integer cno, @Param("tsno") Integer tsno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "sno, cno, tsno, score",
        "from score"
    })
    @ConstructorArgs({
        @Arg(column="sno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="cno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="tsno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="score", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    List<Score> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Update({
        "update score",
        "set score = #{score,jdbcType=INTEGER}",
        "where sno = #{sno,jdbcType=INTEGER}",
          "and cno = #{cno,jdbcType=INTEGER}",
          "and tsno = #{tsno,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Score record);
}