package cn.edu.buu.uoes.dao;

import cn.edu.buu.uoes.pojo.Selection;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface SelectionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selection
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Delete({
        "delete from selection",
        "where seno = #{seno,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer seno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selection
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Insert({
        "insert into selection (seno, select_text, ",
        "status, qno)",
        "values (#{seno,jdbcType=INTEGER}, #{selectText,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=INTEGER}, #{qno,jdbcType=INTEGER})"
    })
    int insert(Selection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selection
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "seno, select_text, status, qno",
        "from selection",
        "where seno = #{seno,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="seno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="select_text", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="status", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="qno", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    Selection selectByPrimaryKey(Integer seno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selection
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "seno, select_text, status, qno",
        "from selection"
    })
    @ConstructorArgs({
        @Arg(column="seno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="select_text", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="status", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="qno", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    List<Selection> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selection
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Update({
        "update selection",
        "set select_text = #{selectText,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "qno = #{qno,jdbcType=INTEGER}",
        "where seno = #{seno,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Selection record);
}