package cn.edu.buu.uoes.dao;

import cn.edu.buu.uoes.pojo.Student;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface StudentDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Delete({
        "delete from student",
        "where sno = #{sno,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Insert({
        "insert into student (sno, student_name, ",
        "sex, clno)",
        "values (#{sno,jdbcType=INTEGER}, #{studentName,jdbcType=VARCHAR}, ",
        "#{sex,jdbcType=VARCHAR}, #{clno,jdbcType=INTEGER})"
    })
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "sno, student_name, sex, clno",
        "from student",
        "where sno = #{sno,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="sno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="student_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="sex", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="clno", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    Student selectByPrimaryKey(Integer sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "sno, student_name, sex, clno",
        "from student"
    })
    @ConstructorArgs({
        @Arg(column="sno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="student_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="sex", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="clno", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    List<Student> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Update({
        "update student",
        "set student_name = #{studentName,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=VARCHAR},",
          "clno = #{clno,jdbcType=INTEGER}",
        "where sno = #{sno,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Student record);
}