package cn.edu.buu.uoes.dao;

import cn.edu.buu.uoes.pojo.Test;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TestDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Delete({
        "delete from test",
        "where tsno = #{tsno,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer tsno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Insert({
        "insert into test (tsno, eno, ",
        "clno, start_time, ",
        "end_time)",
        "values (#{tsno,jdbcType=INTEGER}, #{eno,jdbcType=INTEGER}, ",
        "#{clno,jdbcType=INTEGER}, #{startTime,jdbcType=TIMESTAMP}, ",
        "#{endTime,jdbcType=TIMESTAMP})"
    })
    int insert(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "tsno, eno, clno, start_time, end_time",
        "from test",
        "where tsno = #{tsno,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="tsno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="eno", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="clno", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="start_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="end_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP)
    })
    Test selectByPrimaryKey(Integer tsno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "tsno, eno, clno, start_time, end_time",
        "from test"
    })
    @ConstructorArgs({
        @Arg(column="tsno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="eno", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="clno", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="start_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="end_time", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP)
    })
    List<Test> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Update({
        "update test",
        "set eno = #{eno,jdbcType=INTEGER},",
          "clno = #{clno,jdbcType=INTEGER},",
          "start_time = #{startTime,jdbcType=TIMESTAMP},",
          "end_time = #{endTime,jdbcType=TIMESTAMP}",
        "where tsno = #{tsno,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Test record);
}