package cn.edu.buu.uoes.dao;

import cn.edu.buu.uoes.pojo.User;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface UserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Delete({
        "delete from user",
        "where uno = #{uno,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer uno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Insert({
        "insert into user (uno, password, ",
        "authority)",
        "values (#{uno,jdbcType=INTEGER}, #{password,jdbcType=VARCHAR}, ",
        "#{authority,jdbcType=INTEGER})"
    })
    @Options(useGeneratedKeys = true, keyColumn = "uno", keyProperty = "uno")
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "uno, password, authority",
        "from user",
        "where uno = #{uno,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="uno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="password", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="authority", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    User selectByPrimaryKey(Integer uno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Select({
        "select",
        "uno, password, authority",
        "from user"
    })
    @ConstructorArgs({
        @Arg(column="uno", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="password", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="authority", javaType=Integer.class, jdbcType=JdbcType.INTEGER)
    })
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    @Update({
        "update user",
        "set password = #{password,jdbcType=VARCHAR},",
          "authority = #{authority,jdbcType=INTEGER}",
        "where uno = #{uno,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(User record);
}