package cn.edu.buu.uoes.pojo;

public class ClassCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_course.clno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer clno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_course.cno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer cno;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public ClassCourse(Integer clno, Integer cno) {
        this.clno = clno;
        this.cno = cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public ClassCourse() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_course.clno
     *
     * @return the value of class_course.clno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getClno() {
        return clno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_course.clno
     *
     * @param clno the value for class_course.clno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setClno(Integer clno) {
        this.clno = clno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_course.cno
     *
     * @return the value of class_course.cno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_course.cno
     *
     * @param cno the value for class_course.cno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setCno(Integer cno) {
        this.cno = cno;
    }
}