package cn.edu.buu.uoes.pojo;

public class Classes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.clno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer clno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.class_name
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.tno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer tno;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Classes(Integer clno, String className, Integer tno) {
        this.clno = clno;
        this.className = className;
        this.tno = tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Classes() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.clno
     *
     * @return the value of classes.clno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getClno() {
        return clno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.clno
     *
     * @param clno the value for classes.clno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setClno(Integer clno) {
        this.clno = clno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.class_name
     *
     * @return the value of classes.class_name
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.class_name
     *
     * @param className the value for classes.class_name
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.tno
     *
     * @return the value of classes.tno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.tno
     *
     * @param tno the value for classes.tno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setTno(Integer tno) {
        this.tno = tno;
    }
}