package cn.edu.buu.uoes.pojo;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer cno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_name
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.tno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer tno;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Course(Integer cno, String courseName, Integer tno) {
        this.cno = cno;
        this.courseName = courseName;
        this.tno = tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Course() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cno
     *
     * @return the value of course.cno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cno
     *
     * @param cno the value for course.cno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setCno(Integer cno) {
        this.cno = cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_name
     *
     * @return the value of course.course_name
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_name
     *
     * @param courseName the value for course.course_name
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.tno
     *
     * @return the value of course.tno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.tno
     *
     * @param tno the value for course.tno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setTno(Integer tno) {
        this.tno = tno;
    }
}