package cn.edu.buu.uoes.pojo;

public class ExamQuestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_question.eno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer eno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_question.qno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer qno;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public ExamQuestion(Integer eno, Integer qno) {
        this.eno = eno;
        this.qno = qno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_question
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public ExamQuestion() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_question.eno
     *
     * @return the value of exam_question.eno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getEno() {
        return eno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_question.eno
     *
     * @param eno the value for exam_question.eno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setEno(Integer eno) {
        this.eno = eno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_question.qno
     *
     * @return the value of exam_question.qno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getQno() {
        return qno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_question.qno
     *
     * @param qno the value for exam_question.qno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setQno(Integer qno) {
        this.qno = qno;
    }
}