package cn.edu.buu.uoes.pojo;

public class Exam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.eno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer eno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.cno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer cno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.point
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer point;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Exam(Integer eno, Integer cno, Integer point) {
        this.eno = eno;
        this.cno = cno;
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Exam() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.eno
     *
     * @return the value of exam.eno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getEno() {
        return eno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.eno
     *
     * @param eno the value for exam.eno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setEno(Integer eno) {
        this.eno = eno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.cno
     *
     * @return the value of exam.cno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.cno
     *
     * @param cno the value for exam.cno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setCno(Integer cno) {
        this.cno = cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.point
     *
     * @return the value of exam.point
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.point
     *
     * @param point the value for exam.point
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setPoint(Integer point) {
        this.point = point;
    }
}