package cn.edu.buu.uoes.pojo;

import java.util.Date;

public class Note {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.nno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer nno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.note_text
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private String noteText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.nsend_user
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer nsendUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.nget_user
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer ngetUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.time
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Note(Integer nno, String noteText, Integer nsendUser, Integer ngetUser, Date time) {
        this.nno = nno;
        this.noteText = noteText;
        this.nsendUser = nsendUser;
        this.ngetUser = ngetUser;
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Note() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.nno
     *
     * @return the value of note.nno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getNno() {
        return nno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.nno
     *
     * @param nno the value for note.nno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setNno(Integer nno) {
        this.nno = nno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.note_text
     *
     * @return the value of note.note_text
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public String getNoteText() {
        return noteText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.note_text
     *
     * @param noteText the value for note.note_text
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setNoteText(String noteText) {
        this.noteText = noteText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.nsend_user
     *
     * @return the value of note.nsend_user
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getNsendUser() {
        return nsendUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.nsend_user
     *
     * @param nsendUser the value for note.nsend_user
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setNsendUser(Integer nsendUser) {
        this.nsendUser = nsendUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.nget_user
     *
     * @return the value of note.nget_user
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getNgetUser() {
        return ngetUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.nget_user
     *
     * @param ngetUser the value for note.nget_user
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setNgetUser(Integer ngetUser) {
        this.ngetUser = ngetUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.time
     *
     * @return the value of note.time
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.time
     *
     * @param time the value for note.time
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}