package cn.edu.buu.uoes.pojo;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.qno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer qno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.type
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.cno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer cno;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Question(Integer qno, String question, Integer type, Integer cno) {
        this.qno = qno;
        this.question = question;
        this.type = type;
        this.cno = cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Question() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.qno
     *
     * @return the value of question.qno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getQno() {
        return qno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.qno
     *
     * @param qno the value for question.qno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setQno(Integer qno) {
        this.qno = qno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question
     *
     * @return the value of question.question
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question
     *
     * @param question the value for question.question
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.type
     *
     * @return the value of question.type
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.type
     *
     * @param type the value for question.type
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.cno
     *
     * @return the value of question.cno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.cno
     *
     * @param cno the value for question.cno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setCno(Integer cno) {
        this.cno = cno;
    }
}