package cn.edu.buu.uoes.pojo;

public class Score {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.sno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer sno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.cno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer cno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.tsno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer tsno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.score
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Score(Integer sno, Integer cno, Integer tsno, Integer score) {
        this.sno = sno;
        this.cno = cno;
        this.tsno = tsno;
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Score() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.sno
     *
     * @return the value of score.sno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.sno
     *
     * @param sno the value for score.sno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.cno
     *
     * @return the value of score.cno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.cno
     *
     * @param cno the value for score.cno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setCno(Integer cno) {
        this.cno = cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.tsno
     *
     * @return the value of score.tsno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getTsno() {
        return tsno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.tsno
     *
     * @param tsno the value for score.tsno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setTsno(Integer tsno) {
        this.tsno = tsno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.score
     *
     * @return the value of score.score
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.score
     *
     * @param score the value for score.score
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}