package cn.edu.buu.uoes.pojo;

public class Selection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selection.seno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer seno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selection.select_text
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private String selectText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selection.status
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selection.qno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer qno;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selection
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Selection(Integer seno, String selectText, Integer status, Integer qno) {
        this.seno = seno;
        this.selectText = selectText;
        this.status = status;
        this.qno = qno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selection
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Selection() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selection.seno
     *
     * @return the value of selection.seno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getSeno() {
        return seno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selection.seno
     *
     * @param seno the value for selection.seno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setSeno(Integer seno) {
        this.seno = seno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selection.select_text
     *
     * @return the value of selection.select_text
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public String getSelectText() {
        return selectText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selection.select_text
     *
     * @param selectText the value for selection.select_text
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setSelectText(String selectText) {
        this.selectText = selectText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selection.status
     *
     * @return the value of selection.status
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selection.status
     *
     * @param status the value for selection.status
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selection.qno
     *
     * @return the value of selection.qno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getQno() {
        return qno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selection.qno
     *
     * @param qno the value for selection.qno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setQno(Integer qno) {
        this.qno = qno;
    }
}