package cn.edu.buu.uoes.pojo;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer sno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_name
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sex
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.clno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer clno;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Student(Integer sno, String studentName, String sex, Integer clno) {
        this.sno = sno;
        this.studentName = studentName;
        this.sex = sex;
        this.clno = clno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Student() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sno
     *
     * @return the value of student.sno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sno
     *
     * @param sno the value for student.sno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_name
     *
     * @return the value of student.student_name
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_name
     *
     * @param studentName the value for student.student_name
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sex
     *
     * @return the value of student.sex
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sex
     *
     * @param sex the value for student.sex
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.clno
     *
     * @return the value of student.clno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getClno() {
        return clno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.clno
     *
     * @param clno the value for student.clno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setClno(Integer clno) {
        this.clno = clno;
    }
}