package cn.edu.buu.uoes.pojo;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer tno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_name
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private String teacherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.sex
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_tel
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private String teacherTel;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Teacher(Integer tno, String teacherName, String sex, String teacherTel) {
        this.tno = tno;
        this.teacherName = teacherName;
        this.sex = sex;
        this.teacherTel = teacherTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Teacher() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tno
     *
     * @return the value of teacher.tno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tno
     *
     * @param tno the value for teacher.tno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setTno(Integer tno) {
        this.tno = tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_name
     *
     * @return the value of teacher.teacher_name
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_name
     *
     * @param teacherName the value for teacher.teacher_name
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.sex
     *
     * @return the value of teacher.sex
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.sex
     *
     * @param sex the value for teacher.sex
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_tel
     *
     * @return the value of teacher.teacher_tel
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public String getTeacherTel() {
        return teacherTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_tel
     *
     * @param teacherTel the value for teacher.teacher_tel
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setTeacherTel(String teacherTel) {
        this.teacherTel = teacherTel;
    }
}