package cn.edu.buu.uoes.pojo;

import java.util.Date;

public class Test {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.tsno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer tsno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.eno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer eno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.clno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer clno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.start_time
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.end_time
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Test(Integer tsno, Integer eno, Integer clno, Date startTime, Date endTime) {
        this.tsno = tsno;
        this.eno = eno;
        this.clno = clno;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Test() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.tsno
     *
     * @return the value of test.tsno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getTsno() {
        return tsno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.tsno
     *
     * @param tsno the value for test.tsno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setTsno(Integer tsno) {
        this.tsno = tsno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.eno
     *
     * @return the value of test.eno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getEno() {
        return eno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.eno
     *
     * @param eno the value for test.eno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setEno(Integer eno) {
        this.eno = eno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.clno
     *
     * @return the value of test.clno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getClno() {
        return clno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.clno
     *
     * @param clno the value for test.clno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setClno(Integer clno) {
        this.clno = clno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.start_time
     *
     * @return the value of test.start_time
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.start_time
     *
     * @param startTime the value for test.start_time
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.end_time
     *
     * @return the value of test.end_time
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.end_time
     *
     * @param endTime the value for test.end_time
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}