package cn.edu.buu.uoes.pojo;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer uno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.authority
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    private Integer authority;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public User(Integer uno, String password, Integer authority) {
        this.uno = uno;
        this.password = password;
        this.authority = authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uno
     *
     * @return the value of user.uno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getUno() {
        return uno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uno
     *
     * @param uno the value for user.uno
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setUno(Integer uno) {
        this.uno = uno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.authority
     *
     * @return the value of user.authority
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public Integer getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.authority
     *
     * @param authority the value for user.authority
     *
     * @mbg.generated Mon Oct 05 16:05:59 CST 2020
     */
    public void setAuthority(Integer authority) {
        this.authority = authority;
    }
}